services:
  # Backend API (override for production)
  backend:
    # Do not expose backend to the public internet in production
    ports: []
    environment:
      TRUST_PROXY: 1
      FRONTEND_URL: https://app.golf-rougemont.com
      # En production, limiter strictement aux origines HTTPS du domaine
      CORS_ORIGINS: https://app.golf-rougemont.com

  # Database (override for production)
  # Ensure MongoDB is not exposed publicly
  # This overrides the base compose which maps 27017:27017 in dev
  database:
    ports: []

  # Frontend (Nginx serving React build)
  frontend:
    # Ne pas exposer publiquement: Caddy (service dédié) exposera 80/443 et proxy vers frontend
    ports: []
    # - "443:443"  # Enable only if you manage certificates inside this container
    # Use a production Nginx config that proxies /api/ to the backend container
    volumes:
      - ./frontend/nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
    build:
      args:
        # Same-origin: frontend calls /api which Nginx proxies to backend
        VITE_API_URL: /api
        # Timeout global Axios en prod (override possible via env: VITE_API_TIMEOUT_MS)
        VITE_API_TIMEOUT_MS: ${VITE_API_TIMEOUT_MS:-20000}
    environment:
      - NODE_ENV=production

  # Reverse proxy HTTPS (Caddy) — termine TLS et reverse proxy vers frontend
  caddy:
    image: caddy:latest
    container_name: fairway-caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
    networks:
      - default

volumes:
  caddy_data:
  caddy_config:
