services:
  # Backend API (override for production)
  backend:
    # Do not expose backend to the public internet in production
    ports: []
    environment:
      TRUST_PROXY: 1
      FRONTEND_URL: https://app.golf-rougemont.com
      # En production, limiter strictement aux origines HTTPS du domaine
      CORS_ORIGINS: https://app.golf-rougemont.com

  # Database (override for production)
  # Ensure MongoDB is not exposed publicly
  # This overrides the base compose which maps 27017:27017 in dev
  database:
    ports: []

  # Frontend (Nginx serving React build with TLS)
  frontend:
<<<<<<< HEAD
    # Expose directly (TLS géré dans ce conteneur)
    ports:
      - "80:80"
      - "443:443"
    # Utiliser la configuration Nginx TLS et monter les certificats
    volumes:
      - ./frontend/nginx/default.tls.conf:/etc/nginx/conf.d/default.conf:ro
      - ./secrets/tls/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./secrets/tls/privkey.pem:/etc/nginx/certs/privkey.pem:ro
=======
    # Expose 80/443 directly (TLS terminated inside this container)
    ports:
      - "80:80"
      - "443:443"
    # Use TLS-enabled Nginx config and mount certificates directory
    volumes:
      - ./frontend/nginx/default.tls.conf:/etc/nginx/conf.d/default.conf:ro
      - ${TLS_CERTS_DIR:-./secrets/tls}:/etc/nginx/certs:ro
      # ACME webroot served by Nginx for Certbot renewals (host path mounted read-only in container)
      - ${CERTBOT_WEBROOT_DIR:-/var/www/certbot}:/var/www/certbot:ro
>>>>>>> 9fea6b1 (feat: implement TLS termination in frontend Nginx container with Let's Encrypt support)
    build:
      args:
        # Same-origin: frontend calls /api which Nginx proxies to backend
        VITE_API_URL: /api
        # Timeout global Axios en prod (override possible via env: VITE_API_TIMEOUT_MS)
        VITE_API_TIMEOUT_MS: ${VITE_API_TIMEOUT_MS:-20000}
    environment:
      - NODE_ENV=production
<<<<<<< HEAD
=======

>>>>>>> 9fea6b1 (feat: implement TLS termination in frontend Nginx container with Let's Encrypt support)
