name: backend-install (manual)

on:
  # Désactivé par défaut; lancer manuellement si besoin
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: backend/package-lock.json
          registry-url: https://registry.npmjs.org/

      - name: Force public npm registry
        run: echo "registry=https://registry.npmjs.org/" > ~/.npmrc

      - name: Clean npm cache
        run: rm -rf ~/.npm/_cacache || true

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
