name: backend-install

on:
  push:
    branches: [ main, develop, "feature/**" ]
    paths:
      - "backend/**"
      - ".github/workflows/backend-install.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "backend/**"
      - ".github/workflows/backend-install.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: |
          npm ci || npm install
