name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
          registry-url: https://registry.npmjs.org/
      - name: Force public npm registry
        run: echo "registry=https://registry.npmjs.org/" > ~/.npmrc
      - name: Install dependencies (clean, avoid npm ci lock mismatch)
        run: |
          rm -rf node_modules package-lock.json
          rm -rf ~/.npm/_cacache || true
          npm install

  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          registry-url: https://registry.npmjs.org/
      - name: Force public npm registry
        run: echo "registry=https://registry.npmjs.org/" > ~/.npmrc
      - name: Install dependencies (clean workaround for npm optional deps bug)
        run: |
          rm -rf node_modules package-lock.json
          rm -rf ~/.npm/_cacache || true
          npm install
      - name: Ensure Rollup native binary on Linux
        if: runner.os == 'Linux'
        run: |
          npm install --no-save @rollup/rollup-linux-x64-gnu@^4.24.0
      - name: Build
        run: npm run build
        env:
          # Backend mounts routes under /api/* (see backend/src/index.js) and Nginx proxies /api -> backend
          VITE_API_URL: /api
