name: deploy-prod

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'frontend/nginx/**'
      - 'docker-compose.yml'
      - 'docker-compose.prod.yml'
      - '.github/workflows/deploy-prod.yml'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Pourquoi lancer le déploiement manuellement? (optionnel)'
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional: build check to fail fast if frontend fails to build with /api
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Frontend build sanity check
        env:
          VITE_API_URL: /api
        run: |
          cd frontend
          rm -rf node_modules package-lock.json ~/.npm/_cacache || true
          npm install
          npm run build

      - name: Validate required deployment secrets
        shell: bash
        run: |
          set -euo pipefail
          missing=()
          [[ -z "${{ secrets.VPS_HOST }}" ]] && missing+=(VPS_HOST)
          [[ -z "${{ secrets.VPS_USER }}" ]] && missing+=(VPS_USER)
          [[ -z "${{ secrets.VPS_SSH_KEY }}" ]] && missing+=(VPS_SSH_KEY)
          [[ -z "${{ secrets.VPS_APP_DIR }}" ]] && missing+=(VPS_APP_DIR)
          if (( ${#missing[@]} > 0 )); then
            echo "Missing required secrets: ${missing[*]}" >&2
            exit 1
          fi
      # SCP step removed: move to git-based deployment on the VPS

      - name: Deploy on VPS with Docker Compose (prod)
        uses: appleboy/ssh-action@v1.2.0
        env:
          VPS_APP_DIR: ${{ secrets.VPS_APP_DIR }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          envs: VPS_APP_DIR
          script: |
            set -e
            cd "$VPS_APP_DIR"
            [ -d .git ]
            [ -f .env ]
            git fetch --all --prune
            git reset --hard origin/main
            docker compose -f docker-compose.yml -f docker-compose.prod.yml pull || true
            docker compose -f docker-compose.yml -f docker-compose.prod.yml build --pull
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --remove-orphans
            docker system prune -f || true
