name: frontend-build

on:
  push:
    branches: [ main, develop, "feature/**" ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-build.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-build.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies (clean workaround for npm optional deps bug)
        # Contexte: npm peut ne pas installer les optionalDependencies spécifiques à la plateforme
        # (ex: @rollup/rollup-linux-x64-gnu) lorsqu'un package-lock.json généré sur un autre OS est présent.
        # Voir: https://github.com/npm/cli/issues/4828
        # Solution: installation propre sans lock existant pour laisser npm résoudre les binaires natifs Linux.
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Ensure Rollup native binary on Linux
        if: runner.os == 'Linux'
        run: |
          npm install --no-save @rollup/rollup-linux-x64-gnu@^4.24.0

      - name: Build (Vite)
        env:
          VITE_API_URL: /api/v1
        run: npm run build
